# @package _global_.model

type: cnn_unet_transformer
in_channels: 5
out_channels: 2

# stem
stem_channels: 32

# UNet
base_channels: 64
depth: 4

# ViT
vit_dim: 256
vit_layers: 4
vit_heads: 4
patch_size: 1
