# configs/model/fno_transformer.yaml
type: fno_transformer

# ---- FNO ---------------------------------------------------------
modes:       12      # spectral modes per dimension
fno_depth:   4
fno_width:   64

# ---- Transformer -------------------------------------------------
embed_dim:   128     # 128 fits comfortably on a 12 GB RTX 3060
trans_depth: 4
n_heads:     8
mlp_dim:     256
dropout:     0.1

