# @package _global_.model

type: fno_transformer

width: 48          # hidden channels (memory-fit)
depth_fno: 4
modes_y: 12
modes_x: 18
pool: 2            # ↓ tokens to 864
trans_layers: 2
n_heads: 4
trans_mlp: 192
dropout: 0.1
