# @package _global_

defaults:
  - data: data
  - model: precip_enhanced_model # Must change 
  - training: default
  - trainer: default
  - _self_

# Global configs
seed: 42


# Wandb logging, all arguments are only used if use_wandb is set to true
use_wandb: true
wandb_project: "cse-151b-competition"
wandb_entity: jokestar
run_name: null

# Path to a checkpoint to load. If set, will load this checkpoint and resume training (evaluation)
ckpt_path: null
# ./outputs/2025-05-28/22-36-10/checkpoints/epoch=epoch=49-step=step=7100.ckpt


hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

