# @package _global_

defaults:
  - data: data
  - model: Cnn_transformer_attention # Must change 
  - training: default
  - trainer: default
  - _self_

# Global configs
seed: 42

# Normalization
normalization:
  input_transforms:
    CO2 : zscore
    CH4 : zscore
    SO2 : cube_root     
    BC  : cube_root
    rsdt: zscore
  output_transforms:
    tas: zscore
    pr : log_zscore       # x ** (1/3); better than raw or pure log for near-zero

# Wandb logging, all arguments are only used if use_wandb is set to true
use_wandb: true
wandb_project: "cse-151b-competition"
wandb_entity: jokestar
run_name: null

# Path to a checkpoint to load. If set, will load this checkpoint and resume training (evaluation)
ckpt_path: null

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

