# @package _global_

defaults:
  - data: data
  - model: climate_transformer # Must change 
  - training: uvit_cosine
  - trainer: uvit_cosine
  - _self_

# Global configs
seed: 42

# Wandb logging, all arguments are only used if use_wandb is set to true
use_wandb: true
wandb_project: "cse-151b-competition"
wandb_entity: jokestar
run_name: null

# Path to a checkpoint to load. If set, will load this checkpoint and resume training (evaluation)
ckpt_path: null
# ./outputs/2025-05-27/09-22-26/checkpoints/last.ckpt
# ./outputs/2025-05-27/09-04-20/checkpoints/epoch=epoch=19-step=step=920.ckpt
hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

